" set hidden
set nocompatible               " be iMproved
filetype off                   " required!

set expandtab		       " convert tab to spaces

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle, required! 
Bundle 'gmarik/vundle'

" My bundles
" Syntastic - static syntax checkers
Bundle 'scrooloose/syntastic'
" Do not check syntax in case of :wq and like
let g:syntastic_check_on_wq=0
let g:syntastic_enable_balloons = 0 " no mouse balloons
let g:syntastic_echo_current_error=0 " no error echo

Bundle 'scrooloose/nerdtree'
nmap \e :NERDTreeToggle<CR>

" Snipmate dependencies
Bundle "MarcWeber/vim-addon-mw-utils"
Bundle "tomtom/tlib_vim"
Bundle "honza/vim-snippets"
" Snipmate 
Bundle 'garbas/vim-snipmate'

" Powerline
Bundle 'Lokaltog/powerline'
set rtp+=~/.vim/bundle/powerline/powerline/bindings/vim
set laststatus=2 "Always display statusline in all windows
set noshowmode	"Hide the default mode text
" Make powerline colorfule
if $TERM == "xterm-256color" || $TERM == "screen-256color" || $COLORTERM == "gnome-terminal"
	set t_Co=256
endif

filetype plugin indent on
