export ANTIGEN_DEFAULT_REPO_URL=https://github.com/szferi/oh-my-zsh.git
source $HOME/antigen/antigen.zsh

# Load the oh-my-zsh's library.
antigen use oh-my-zsh

# Bundles
# General
antigen bundle command-not-found       # zsh support for ubuntu's command-not-found package
# SCM
antigen bundle git   # shortcuts and prompt decore
antigen bundle szferi/oh-my-zsh plugins/mercurial   # shortcuts and git compatible prompt decore

# Python support
antigen bundle python      # pyfind, pygrep, pyclean
antigen bundle virtualenv  # provides pompt decorator function
if [ ! -d $HOME/env ]; then
        mkdir -p $HOME/env
fi
export WORKON_HOME=$HOME/envs     # set home for virtualenv environments
export DISABLE_VENV_CD=1          # turn of auto enviroment activition feature of virtualenvwrapper plugin
export VIRTUALENV_DISTRIBUTE=1    # make distribute (instead of setuptools) the default 
                                  # fortunately the --no-site-packages is default for a while
antigen bundle virtualenvwrapper  # workon 
antigen bundle pip                # autocompletion for pip

# Vim/vundle
antigen bundle vundle      # activate vundle and provide vundle-{install,update,clean} functions
# Thene
antigen theme szferi/dotfiles zsh/themes/szferi.zsh-theme

# powerline
#export PATH=$PATH:$HOME/.vim/bundle/powerline/scripts
#source $HOME/.vim/bundle/powerline/powerline/bindings/zsh/powerline.zsh

# Apply
antigen apply
